### ISSUE TITLE
Public release of official implementation

### ISSUE THREAD

**Issue by cgrx** [ETHRuiGong/mDALU#1]
I was reading your paper [1] and stumbled upon your repo. I would like to know if you are still planning to release the official implementation of the code. 

[1]  R. Gong, D. Dai, Y. Chen, W. Li, and L. Van Gool, “mDALU: Multi-Source Domain Adaptation and Label Unification with Partial Datasets,” in Proceedings of the IEEE/CVF International Conference on Computer Vision, 2021, pp. 8876–8885.

**Comment by ETHRuiGong** [comment]
Hi,

I am sorry that I am too busy with other works now and do not find much time to clean the code. If you need the code, please send me an e-mail (gongr@vision.ee.ethz.ch). The code is a little messy, but is able to be run as your baseline.

Thanks a lot!

Best,
Rui

**Comment by cgrx** [comment]
Thanks a bunch ! That will be immensely useful for my research. Will definitely send you an email.
